"""initial schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_project_id'), ['project_id'], unique=False)

    op.create_table('change_log',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('op', sa.String(length=10), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('seq')
    )
    with op.batch_alter_table('change_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_log_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_change_project_seq', ['project_id', 'seq'], unique=False)

    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('exp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('jti')
    )
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_tokens_exp'), ['exp'], unique=False)

    op.create_table('sync_ops',
    sa.Column('op_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('op_type', sa.String(length=40), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('op_id', 'user_id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_created_by'), ['created_by'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('element_id', sa.String(length=36), nullable=True),
    sa.Column('test_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=36), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alert_project_created', ['project_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_project_id'), ['project_id'], unique=False)

    op.create_table('batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('batch_code', sa.String(length=40), nullable=False),
    sa.Column('public_token', sa.String(length=24), nullable=False),
    sa.Column('material', sa.String(length=30), nullable=False),
    sa.Column('construction_type', sa.String(length=10), nullable=False),
    sa.Column('grade', sa.String(length=6), nullable=False),
    sa.Column('fck', sa.Float(), nullable=False),
    sa.Column('exposure', sa.String(length=20), nullable=False),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('supplier_ref', sa.String(length=100), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('quantity_m3', sa.Float(), nullable=False),
    sa.Column('cement_type', sa.String(length=10), nullable=False),
    sa.Column('cement_content_kg_m3', sa.Float(), nullable=True),
    sa.Column('wc_ratio', sa.Float(), nullable=True),
    sa.Column('admixture', sa.String(length=200), nullable=True),
    sa.Column('mix_notes', sa.Text(), nullable=True),
    sa.Column('registration_check', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status in ('PENDING','VERIFIED','REVIEW_REQUIRED','FLAGGED')", name='ck_batch_status'),
    sa.CheckConstraint('quantity_m3 >= 0', name='ck_batch_qty'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index('ix_batch_project_created', ['project_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_batch_code'), ['batch_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_batches_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_public_token'), ['public_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_batches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_supplier'), ['supplier'], unique=False)

    op.create_table('buildings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buildings_project_id'), ['project_id'], unique=False)

    op.create_table('project_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id')
    )
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_members_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_members_user_id'), ['user_id'], unique=False)

    op.create_table('floors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('building_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('floors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_floors_building_id'), ['building_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_floors_project_id'), ['project_id'], unique=False)

    op.create_table('investigations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('closure_note', sa.Text(), nullable=True),
    sa.Column('opened_by', sa.String(length=36), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigations_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_opened_by'), ['opened_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_status'), ['status'], unique=False)

    op.create_table('samples',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('sample_code', sa.String(length=50), nullable=False),
    sa.Column('cast_date', sa.Date(), nullable=False),
    sa.Column('cubes_cast', sa.Integer(), nullable=False),
    sa.Column('curing_method', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_samples_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_samples_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_samples_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_samples_sample_code'), ['sample_code'], unique=True)

    op.create_table('elements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('floor_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('element_type', sa.String(length=30), nullable=False),
    sa.Column('exposure', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['floor_id'], ['floors.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('elements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_elements_floor_id'), ['floor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_elements_project_id'), ['project_id'], unique=False)

    op.create_table('investigation_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=40), nullable=False),
    sa.Column('element_id', sa.String(length=36), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result_test_id', sa.String(length=36), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigation_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigation_actions_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('test_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('sample_id', sa.String(length=36), nullable=True),
    sa.Column('test_type', sa.String(length=40), nullable=False),
    sa.Column('age_days', sa.Integer(), nullable=True),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('lab_name', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tested_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('review', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('supersedes_id', sa.String(length=36), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('record_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status in ('VERIFIED','REVIEW_REQUIRED','FLAGGED')", name='ck_test_status'),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('test_records', schema=None) as batch_op:
        batch_op.create_index('ix_test_batch_current', ['batch_id', 'is_current'], unique=False)
        batch_op.create_index('ix_test_project_current', ['project_id', 'is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_records_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_records_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_records_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_records_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_records_sample_id'), ['sample_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_test_records_test_type'), ['test_type'], unique=False)

    op.create_table('batch_usages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('element_id', sa.String(length=36), nullable=False),
    sa.Column('volume_m3', sa.Float(), nullable=True),
    sa.Column('poured_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_usages_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_usages_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_usages_element_id'), ['element_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_batch_usages_project_id'), ['project_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('sample_id', sa.String(length=36), nullable=True),
    sa.Column('test_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=400), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['test_records.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_sample_id'), ['sample_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_test_id'), ['test_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_uploaded_by'), ['uploaded_by'], unique=False)

    op.create_table('observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('element_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index('ix_obs_element_kind_time', ['element_id', 'kind', 'observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_element_id'), ['element_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_observed_at'), ['observed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_project_id'), ['project_id'], unique=False)

    op.create_table('risk_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('element_id', sa.String(length=36), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('trend', sa.String(length=20), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('anomalies', sa.JSON(), nullable=False),
    sa.Column('recommendations', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['elements.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_assessments_computed_at'), ['computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_element_id'), ['element_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_assessments_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_risk_element_time', ['element_id', 'computed_at'], unique=False)

    op.create_table('ocr_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('extracted', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('test_id', sa.String(length=36), nullable=True),
    sa.Column('confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocr_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocr_drafts_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ocr_drafts_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ocr_drafts_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocr_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocr_drafts_project_id'))
        batch_op.drop_index(batch_op.f('ix_ocr_drafts_document_id'))
        batch_op.drop_index(batch_op.f('ix_ocr_drafts_created_by'))

    op.drop_table('ocr_drafts')
    with op.batch_alter_table('risk_assessments', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_element_time')
        batch_op.drop_index(batch_op.f('ix_risk_assessments_project_id'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_element_id'))
        batch_op.drop_index(batch_op.f('ix_risk_assessments_computed_at'))

    op.drop_table('risk_assessments')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_project_id'))
        batch_op.drop_index(batch_op.f('ix_observations_observed_at'))
        batch_op.drop_index(batch_op.f('ix_observations_kind'))
        batch_op.drop_index(batch_op.f('ix_observations_element_id'))
        batch_op.drop_index(batch_op.f('ix_observations_created_by'))
        batch_op.drop_index('ix_obs_element_kind_time')

    op.drop_table('observations')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_uploaded_by'))
        batch_op.drop_index(batch_op.f('ix_documents_test_id'))
        batch_op.drop_index(batch_op.f('ix_documents_sample_id'))
        batch_op.drop_index(batch_op.f('ix_documents_project_id'))
        batch_op.drop_index(batch_op.f('ix_documents_batch_id'))

    op.drop_table('documents')
    with op.batch_alter_table('batch_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_usages_project_id'))
        batch_op.drop_index(batch_op.f('ix_batch_usages_element_id'))
        batch_op.drop_index(batch_op.f('ix_batch_usages_created_by'))
        batch_op.drop_index(batch_op.f('ix_batch_usages_batch_id'))

    op.drop_table('batch_usages')
    with op.batch_alter_table('test_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_test_records_test_type'))
        batch_op.drop_index(batch_op.f('ix_test_records_status'))
        batch_op.drop_index(batch_op.f('ix_test_records_sample_id'))
        batch_op.drop_index(batch_op.f('ix_test_records_project_id'))
        batch_op.drop_index(batch_op.f('ix_test_records_is_current'))
        batch_op.drop_index(batch_op.f('ix_test_records_created_by'))
        batch_op.drop_index(batch_op.f('ix_test_records_batch_id'))
        batch_op.drop_index('ix_test_project_current')
        batch_op.drop_index('ix_test_batch_current')

    op.drop_table('test_records')
    with op.batch_alter_table('investigation_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigation_actions_investigation_id'))

    op.drop_table('investigation_actions')
    with op.batch_alter_table('elements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_elements_project_id'))
        batch_op.drop_index(batch_op.f('ix_elements_floor_id'))

    op.drop_table('elements')
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_samples_sample_code'))
        batch_op.drop_index(batch_op.f('ix_samples_project_id'))
        batch_op.drop_index(batch_op.f('ix_samples_created_by'))
        batch_op.drop_index(batch_op.f('ix_samples_batch_id'))

    op.drop_table('samples')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigations_status'))
        batch_op.drop_index(batch_op.f('ix_investigations_project_id'))
        batch_op.drop_index(batch_op.f('ix_investigations_opened_by'))
        batch_op.drop_index(batch_op.f('ix_investigations_batch_id'))

    op.drop_table('investigations')
    with op.batch_alter_table('floors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_floors_project_id'))
        batch_op.drop_index(batch_op.f('ix_floors_building_id'))

    op.drop_table('floors')
    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_members_user_id'))
        batch_op.drop_index(batch_op.f('ix_project_members_project_id'))

    op.drop_table('project_members')
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buildings_project_id'))

    op.drop_table('buildings')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_supplier'))
        batch_op.drop_index(batch_op.f('ix_batches_status'))
        batch_op.drop_index(batch_op.f('ix_batches_public_token'))
        batch_op.drop_index(batch_op.f('ix_batches_project_id'))
        batch_op.drop_index(batch_op.f('ix_batches_created_by'))
        batch_op.drop_index(batch_op.f('ix_batches_batch_code'))
        batch_op.drop_index('ix_batch_project_created')

    op.drop_table('batches')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_project_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_kind'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index('ix_alert_project_created')

    op.drop_table('alerts')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_created_by'))

    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('sync_ops')
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_exp'))

    op.drop_table('revoked_tokens')
    with op.batch_alter_table('change_log', schema=None) as batch_op:
        batch_op.drop_index('ix_change_project_seq')
        batch_op.drop_index(batch_op.f('ix_change_log_project_id'))

    op.drop_table('change_log')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_project_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
