"""ai layer tables

Revision ID: 0003
Revises: 0002
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('doc_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('embedding_model', sa.String(length=80), nullable=True),
    sa.Column('embedding_dims', sa.Integer(), nullable=True),
    sa.Column('chunk_config', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_chunks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_chunks_doc_id'), ['doc_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_chunks_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_chunks_source'), ['source'], unique=False)

    op.create_table('ai_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('endpoint', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('ttft_ms', sa.Integer(), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_request_id'), ['request_id'], unique=False)
        batch_op.create_index('ix_aiusage_user_time', ['user_id', 'created_at'], unique=False)

    op.create_table('ai_conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_conversations_updated_at'), ['updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_conversations_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_aiconv_user_updated', ['user_id', 'updated_at'], unique=False)

    op.create_table('ai_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'content_hash')
    )
    with op.batch_alter_table('ai_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_documents_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_documents_project_id'), ['project_id'], unique=False)

    op.create_table('ai_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=12), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['ai_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index('ix_aimsg_conv_created', ['conversation_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_aimsg_conv_created')
        batch_op.drop_index(batch_op.f('ix_ai_messages_conversation_id'))

    op.drop_table('ai_messages')
    with op.batch_alter_table('ai_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_documents_project_id'))
        batch_op.drop_index(batch_op.f('ix_ai_documents_created_by'))

    op.drop_table('ai_documents')
    with op.batch_alter_table('ai_conversations', schema=None) as batch_op:
        batch_op.drop_index('ix_aiconv_user_updated')
        batch_op.drop_index(batch_op.f('ix_ai_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_conversations_updated_at'))

    op.drop_table('ai_conversations')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index('ix_aiusage_user_time')
        batch_op.drop_index(batch_op.f('ix_ai_usage_request_id'))

    op.drop_table('ai_usage')
    with op.batch_alter_table('ai_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_chunks_source'))
        batch_op.drop_index(batch_op.f('ix_ai_chunks_project_id'))
        batch_op.drop_index(batch_op.f('ix_ai_chunks_doc_id'))

    op.drop_table('ai_chunks')
    # ### end Alembic commands ###
